JENKINS_HOST = 'localhost'
JENKINS_PORT = '8080'
JENKINS_URL = 'http://{}:{}'.format(JENKINS_HOST, JENKINS_PORT)

JENKINS_USER = ''
JENKINS_PASSWORD = ''

DEFAULT_GROUPS_MAP_MODULE_NAME = 'test_groups'
# Name of you own module with test map
GROUPS_MAP_MODULE_NAME = DEFAULT_GROUPS_MAP_MODULE_NAME

DEFAULT_SCENARIO_JOB_NAME = 'test_run'
DEFAULT_SCENARIO_JOB_FILE_NAME = DEFAULT_SCENARIO_JOB_NAME + '_config.xml'
# Name of you own jenkins test job
SCENARIO_JOB_NAME = DEFAULT_SCENARIO_JOB_NAME

JOB_NAME_SEPARATOR = '_'
GROUP_JOB_NAME_PREFIX = GROUPS_MAP_MODULE_NAME

TEMPLATE_JOB_NAME = GROUP_JOB_NAME_PREFIX
TEMPLATE_JOB_FILE_NAME = 'template_job_config.xml'

def create_group_job_name(group_name):
    return JOB_NAME_SEPARATOR.join((GROUP_JOB_NAME_PREFIX, group_name))
